name: AWS Resources Housekeeping

on:
  schedule: # every six hours
    - cron: '0 */6 * * *'

jobs:
  nuke:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup Python
      uses: actions/setup-python@v1
    - name: Install AWS Nuke
      run: pip install aws-nuke
    - name: Nuke Resources
      run: make nuke
